FROM maven:3.3-jdk-8-alpine
WORKDIR /code

ADD ./ECommerce /code/
RUN mvn clean package spring-boot:repackage

EXPOSE 8080
CMD ["java", "-jar", "target/ECommerce-0.0.1-SNAPSHOT.jar", "-Dlog4j.info", "-Dmy.logging.threshold=INFO"]

